package org.zlab.upfuzz.fuzzingengine.trace;

import java.io.Serializable;

/**
 * Phase 0 boundary-resolution primitive.
 *
 * <p>Represents the outcome of mapping a raw {@code nodeId} / {@code peerId}
 * string recorded in a {@link org.zlab.net.tracker.TraceEntry} back to a
 * specific node in the active cluster topology. The bridge accessors
 * generated by {@code nettrace-shuai/rupfuzz-nettrace} expose peers as IPs,
 * hostnames, container aliases, or {@code <executorID>-N<idx>} depending on
 * the target system, so a single raw-id parser cannot cover every case —
 * index parsing is preserved as the strongest path and role-based lookups
 * are layered on top for endpoints that do not carry an explicit index.
 *
 * <p>Resolution tiers, strongest first:
 * <ul>
 *   <li>{@link Resolution#INDEX_RESOLVED} — either numeric parsing ({@code
 *       executor-N<digits>}/{@code N<digits>}/bare digits) or an explicit
 *       topology mapping identified a single node. {@link #nodeIndex} is
 *       authoritative and the endpoint can be used as a boundary
 *       corroborator.</li>
 *   <li>{@link Resolution#ROLE_UNIQUE} — index parsing failed but the raw
 *       id (or its role alias) resolves to a role that only one node in
 *       the active topology carries. {@link #nodeIndex} is populated with
 *       that unique node; role-only resolution is still treated as
 *       corroborating.</li>
 *   <li>{@link Resolution#ROLE_AMBIGUOUS} — the raw id resolves to a role
 *       that multiple nodes share (e.g. Cassandra peer-to-peer or HDFS
 *       "datanode" with more than one data node). The role is known for
 *       diagnostics but the endpoint must not be used as a boundary
 *       corroborator.</li>
 *   <li>{@link Resolution#UNRESOLVED} — no mapping available at all.
 *       Observed as the "silent skip" path that hid Apr16 boundary
 *       traffic; always reported so runs can measure how much traffic
 *       was previously dropped.</li>
 * </ul>
 */
public final class ResolvedTraceEndpoint implements Serializable {
    private static final long serialVersionUID = 20260419L;

    public enum Resolution {
        INDEX_RESOLVED, ROLE_UNIQUE, ROLE_AMBIGUOUS, UNRESOLVED
    }

    public final String rawId;
    public final Resolution resolution;
    /**
     * Node index when {@link #resolution} is {@link Resolution#INDEX_RESOLVED}
     * or {@link Resolution#ROLE_UNIQUE}. {@code -1} when the endpoint could
     * not be pinned to a specific node in the active topology.
     */
    public final int nodeIndex;
    /**
     * Normalized role, when known. May be {@code null} or empty for
     * unresolved endpoints.
     */
    public final String role;

    public ResolvedTraceEndpoint(String rawId, Resolution resolution,
            int nodeIndex, String role) {
        this.rawId = rawId;
        this.resolution = resolution == null ? Resolution.UNRESOLVED
                : resolution;
        this.nodeIndex = nodeIndex;
        this.role = role;
    }

    public static ResolvedTraceEndpoint unresolved(String rawId) {
        return new ResolvedTraceEndpoint(rawId, Resolution.UNRESOLVED, -1,
                null);
    }

    public boolean isCorroborating() {
        return resolution == Resolution.INDEX_RESOLVED
                || resolution == Resolution.ROLE_UNIQUE;
    }

    public boolean hasIndex() {
        return nodeIndex >= 0;
    }

    @Override
    public String toString() {
        return "ResolvedTraceEndpoint{" + rawId + ", " + resolution
                + ", idx=" + nodeIndex + ", role=" + role + "}";
    }
}
